// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'INSERT-APIKEY',
    appId: 'INSERT-APPID',
    messagingSenderId: 'INSERT MESSAGESENDER ID',
    projectId: 'INSERT PROJECT ID',
    authDomain: 'INSERT AUTH DOMAIN',
    storageBucket: 'INSERT BUCKET DOMAIN',
    measurementId: 'INSERT MEASUREMENT ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'INSERT-APIKEY',
    appId: 'INSERT-APPID',
    messagingSenderId: 'INSERT MESSAGESENDER ID',
    projectId: 'INSERT PROJECT ID',
    storageBucket: 'INSERT BUCKET DOMAIN',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'INSERT-APIKEY',
    appId: 'INSERT-APPID',
    messagingSenderId: 'INSERT MESSAGESENDER ID',
    projectId: 'INSERT PROJECT ID',
    storageBucket: 'INSERT BUCKET DOMAIN',
    iosClientId: 'INSERT IOS CLIENT ID',
    iosBundleId: 'INSERT BUNDLE ID',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'INSERT-APIKEY',
    appId: 'INSERT-APPID',
    messagingSenderId: 'INSERT MESSAGESENDER ID',
    projectId: 'INSERT PROJECT ID',
    storageBucket: 'INSERT BUCKET DOMAIN',
    iosClientId: 'INSERT IOS CLIENT ID',
    iosBundleId: 'INSERT BUNDLE ID',
  );
}
